from pathlib import Path

path = Path('index.html')
text = path.read_text(encoding='utf-8')


def one(old, new, label):
    global text
    count = text.count(old)
    if count != 1:
        raise SystemExit(f'{label}: expected 1 occurrence, found {count}')
    text = text.replace(old, new, 1)


one(
    'Multi-manager beta • lineup consensus + simulation • v2.16',
    'Multi-manager beta • lineup consensus + reliable usage • v2.16.1',
    'version subtitle',
)

one(
    'Weekly lineup, matchup, waiver, and roster-management command center. v2.16 adds a two-model Start/Sit consensus layer that cross-checks Weekly Outlook against league-scored projections without blending the two models into fake precision.',
    'Weekly lineup, matchup, waiver, and roster-management command center. v2.16.1 keeps the two-model lineup consensus engine and moves nflverse usage into a same-origin automated snapshot so current-season workload data can load reliably in the browser.',
    'weekly hero copy',
)

old = '''  async function loadUsageSeason(kind,season) {
    const cache=kind==='stats'?state.usageStatsCache:state.usageSnapsCache;
    if(Object.prototype.hasOwnProperty.call(cache,season)) return cache[season];

    const url=kind==='stats'?PLAYER_STATS_URL(season):SNAP_COUNTS_URL(season);
    try {
      const raw=await tgetCached(url);
      const rows=parseCSV(raw);
      cache[season]=rows;
      return rows;
    } catch(e) {
      cache[season]=[];
      return [];
    }
  }
'''

new = '''  async function loadUsageSeason(kind,season) {
    const cache=kind==='stats'?state.usageStatsCache:state.usageSnapsCache;
    if(Object.prototype.hasOwnProperty.call(cache,season)) return cache[season];

    // Prefer the same-origin snapshot generated by GitHub Actions. Direct browser
    // requests to GitHub release assets can fail after redirect/CORS handling even
    // when the nflverse file itself exists.
    try {
      if(!state.usageSnapshot) {
        state.usageSnapshot=await jget(`./data/usage.json?ts=${Date.now()}`);
      }
      const snap=state.usageSnapshot||{};
      const current=Number(season)===Number(snap.season);
      const prior=Number(season)===Number(snap.prior_season);
      const rows=kind==='stats'
        ? (current?snap.current_stats:(prior?snap.prior_stats:[]))
        : (current?snap.current_snaps:(prior?snap.prior_snaps:[]));
      if(Array.isArray(rows) && rows.length) {
        cache[season]=rows;
        return rows;
      }
    } catch(e) {
      state.usageSnapshot=null;
    }

    // Remote fallback remains for development/testing if the hosted snapshot is
    // missing, but normal GitHub Pages operation should not depend on it.
    const url=kind==='stats'?PLAYER_STATS_URL(season):SNAP_COUNTS_URL(season);
    try {
      const raw=await tgetCached(url);
      const rows=parseCSV(raw);
      cache[season]=rows;
      return rows;
    } catch(e) {
      cache[season]=[];
      return [];
    }
  }
'''
one(old, new, 'usage loader')

if "v2.15.3 removes the Aug. 30 draft ECR and preseason news adjustments from Normal Weekly and Trade Intelligence baselines; those draft-era inputs remain isolated to Draft Day and immediate post-draft analysis." in text:
    text = text.replace(
        "v2.15.3 removes the Aug. 30 draft ECR and preseason news adjustments from Normal Weekly and Trade Intelligence baselines; those draft-era inputs remain isolated to Draft Day and immediate post-draft analysis.",
        "v2.15.3 removes the Aug. 30 draft ECR and preseason news adjustments from Normal Weekly and Trade Intelligence baselines; those draft-era inputs remain isolated to Draft Day and immediate post-draft analysis. v2.16.1 snapshots nflverse player stats and snap counts through GitHub Actions so Weekly usage no longer depends on browser fetches to redirected GitHub release assets.",
        1,
    )

if 'v2.16 keeps the Aug. 29/30 half-PPR expert-consensus snapshot isolated to Draft Day and immediate post-draft analysis.' in text:
    text = text.replace(
        'v2.16 keeps the Aug. 29/30 half-PPR expert-consensus snapshot isolated to Draft Day and immediate post-draft analysis.',
        'v2.16.1 keeps the Aug. 29/30 half-PPR expert-consensus snapshot isolated to Draft Day and immediate post-draft analysis.',
        1,
    )

if './data/usage.json?ts=' not in text:
    raise SystemExit('same-origin usage snapshot was not installed')
if 'state.usageSnapshot=await jget' not in text:
    raise SystemExit('usage snapshot loader missing')

path.write_text(text, encoding='utf-8')

changelog = Path('CHANGELOG.md')
cl = changelog.read_text(encoding='utf-8')
if '## v2.16.1 — Usage Snapshot Reliability' not in cl:
    entry = '''## v2.16.1 — Usage Snapshot Reliability
**2026-09-15**

- Fix the Week 2 `usage baseline unavailable` condition caused by browser-time dependency on redirected GitHub release assets.
- Add `scripts/update_usage.py` and a permanent GitHub Actions workflow that snapshots nflverse weekly player stats and snap counts into `data/usage.json` four times per day during NFL-season months.
- Load the same-origin usage snapshot first in Weekly mode, with the previous direct nflverse CSV request retained only as a fallback.
- Store current-season completed-week data plus a compact late-season prior-year fallback so Week 1 can still use a deliberately down-weighted historical workload baseline.
- Preserve the existing usage model, player matching, target/carry/snap calculations, Start/Sit consensus engine, projections, simulation, waiver, trade, news, and availability logic.

'''
    marker = '## v2.16 — Lineup Consensus Engine'
    if marker not in cl:
        raise SystemExit('v2.16 changelog marker missing')
    cl = cl.replace(marker, entry + marker, 1)
    changelog.write_text(cl, encoding='utf-8')
